//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

pub mod prelude;

pub mod anonlogs;
pub mod authorized_users;
pub mod bootlogs;
pub mod devices;
pub mod notes;
pub mod routes;
pub mod segments;
pub mod users;
