//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.1

pub mod prelude;

pub mod anonlogs;
pub mod authorized_users;
pub mod bootlogs;
pub mod device_msg_queues;
pub mod devices;
pub mod routes;
pub mod segments;
pub mod users;
