//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize, Default)]
#[sea_orm(table_name = "users")]
pub struct Model {
    pub created_at: DateTime,
    pub updated_at: DateTime,
    #[sea_orm(primary_key)]
    pub id: i32,
    pub identity: Uuid,
    pub email: Option<String>,
    #[sea_orm(unique)]
    pub name: String,
    pub points: i64,
    pub superuser: bool,
    //pub locations: Option<serde_json::Value>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::authorized_users::Entity")]
    AuthorizedUsers,
    #[sea_orm(has_many = "super::devices::Entity")]
    Devices,
}

impl Related<super::authorized_users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AuthorizedUsers.def()
    }
}

impl Related<super::devices::Entity> for Entity {
    fn to() -> RelationDef {
        super::authorized_users::Relation::Devices.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::authorized_users::Relation::Users.def().rev())
    }
}
