version: '3.2'

services:
  connect:
    image: connect
    build: ..
    ports:
      - "80:80"
    environment:
      COMMA_URL_ROOT: https://connect-api.duckdns.org/
      ATHENA_URL_ROOT: https://connect-api.duckdns.org/ws/
      BILLING_URL_ROOT: https://billing.comma.ai/
      USERADMIN_URL_ROOT: https://connect-useradmin.duckdns.org/

      SENTRY_ENV: connect-development
